# url is the full website URL
# baseurl is the website's URL without the hostname
url: "http://zekariasm.github.io"
baseurl: ""

title: Zekarias M.
#description: We are a group of international experts in infectious disease modelling, Public Health, and software development who collaborate to create the next generation of analysis tools for disease outbreak response using the R software

# List of links in the navigation bar
 navbar-links:
  Blog: ""
  Data Analysis: "DataAnalysis"
  Portfolio: "Portfolio"
  Visualization: "visualization"
  Spatial Analysis: "spatial"

# Change all these values or delete the ones you don't want (these appear in the footer).
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: "Zekarias M."

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  #rss: false
  email: "zekariasmulu@gmail.com"
  #facebook: daattali
  github: zekariasm
# Select which links to show in the footer
footer-links-active:
  github: true
  email: true
  rss: false
  facebook: false
  twitter: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

 Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "http://disqus.com/by/zekiarias_m"

# Google Analytics ID
#google_analytics: "UA-83713279-1"

# Output options (more information on Jekyll's site)
#timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
paginate_path: "/blog/page:num/"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md

gems:
  - jekyll-paginate
